# Build settings
markdown:           kramdown
permalink:          pretty


# Dependencies
markdown:           kramdown
highlighter:        pygments
gems:               [jekyll-paginate]

# Permalinks
permalink:          pretty

# Setup
title:              "English 107"
tagline:
description:        "making things/writing things about literature"
host:               127.0.0.1
url:                ""
baseurl:            "/e107v2"
email:              jloan@pierce.ctc.edu


paginate:           5
layout:             blog-post

# Custom vars
version:            2.0.0
